 curl -v -X POST https://api.line.me/v2/bot/richmenu \
  -H 'Authorization: Bearer YOUR_LINE_CHANNEL_ACCESS_TOKEN' \
  -H 'Content-Type:application/json' \
  -d \
  '{
    "size":{
        "width":2500,
        "height":843
    },
    "selected":true,
    "name":"default2",
    "chatBarText":"menu",
    "areas":[
        {
          "bounds":{
              "x":91,
              "y":258,
              "width":430,
              "height":583
          },
          "action":{
              "type":"postback",
              "data":"r"
          }
        },
        {
          "bounds":{
              "x":697,
              "y":258,
              "width":430,
              "height":583
          },
          "action":{
              "type":"postback",
              "data":"b"
          }
        },
        {
          "bounds":{
              "x":1303,
              "y":258,
              "width":430,
              "height":583
          },
          "action":{
              "type":"postback",
              "data":"w"
          }
        },
        {
          "bounds":{
              "x":1909,
              "y":258,
              "width":430,
              "height":583
          },
          "action":{
              "type":"postback",
              "data":"s"
          }
        }
       ] 
  }'